### ISSUE TITLE
Proper README

### ISSUE THREAD

**Issue by agnlez** [Vizzuality/vizz-components#4]
Add a proper README with installation and use instructions.

I know it's not very difficult to initialize the project at first time, but this project is oriented to everybody regardless his knowledge level... So, let's try to make life easier adding a couple of instructions :D

**Comment by sorodrigo** [comment]
Maybe we could include some example gifs? Would be awesome!

**Comment by oscarferrandiz-zz** [comment]
https://github.com/Vizzuality/vizz-components/pull/6

:*
